### PR TITLE
Japanese pretty (very cute) translation file import function

### PR DESCRIPTION
**Pull request by maboroshin**
In [Forest of Windows](https://forest.watch.impress.co.jp/docs/review/732243.html), Big Japanese software introduce site, is also mentioned LameXP. But it is english software. So I translate it.

I read "Translate.html", Is the upload path correct here?:
"etc\Translation"

"Blank.ts" was in here. I translated this.

### CODE REVIEW

**Comment by lordmulder** [comment]
Thanks! 😎

**Comment by lordmulder** [comment]
Please check new build here:
[LameXP-BETA.2019-10-26.Release-Static.Build-2232.exe](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2019-10-26/LameXP-BETA.2019-10-26.Release-Static.Build-2232.exe/download)

**Comment by maboroshin** [comment]
Okay! Thanks🤑 Good behavior.
I also find Blank.nsh, translating this, please be patient...

**Comment by maboroshin** [comment]
I uploaded to[775b201 in my repository](https://github.com/maboroshin/LameXP/commit/c66031f9f5445126a4a759f9d404974d57c1607d).

- I translated "LameXP_JA.nsh".
- And LameXP_JA.ts: LINE 3386

Add "v" in translation "%1". (fix typo)
```
<source>Convert this file with LameXP v%1</source>
<translation>このファイルを LameXP v%1 で変換</translation>
``

**Comment by lordmulder** [comment]
> 
> 
> I uploaded to[775b201 in my repository](https://github.com/maboroshin/LameXP/commit/c66031f9f5445126a4a759f9d404974d57c1607d).
> 
>     * I translated "LameXP_JA.nsh".
> 
>     * And LameXP_JA.ts: LINE 3386
> 
> 
> Add "v" in translation "%1". (fix typo)
> 
> ```
> <source>Convert this file with LameXP v%1</source>
> <translation>このファイルを LameXP v%1 で変換</translation>
> ``
> ```

Translation has been incorporated into the installer. New TEST build is here:
[LameXP-TEST.2019-10-26.Release-Static.Build-2234.exe](https://sourceforge.net/projects/muldersoft/files/LameXP/Testing/LameXP-TEST.2019-10-26.Release-Static.Build-2234.exe/download)

**Comment by maboroshin** [comment]
I tried. It became completely Japanese.😁

**Comment by maboroshin** [comment]
Sorry. The Minimum and Maximum are reversed.
The following is correct.

```
        <location filename="../../gui/MainWindow.ui" line="1171"/>
        <source>Minimum</source>
        <translation type="unfinished">最低</translation>
    </message>
    <message>
        <location filename="../../gui/MainWindow.ui" line="1181"/>
        <source>Maximum</source>
        <translation type="unfinished">最高</translation>```

**Comment by maboroshin** [comment]
Hi! lordmulder.

I optimized translation for Update Maneger. 
```
        <source>LameXP is free software and release versions won&apos;t expire.</source>
        <translation type="unfinished">LameXP はフリーソフトで正式リリース版の有効期限はありません。</translation>

        <source>Latest version available:</source>
        <translation>利用可能な最新版 :</translation>
        
        <source>We highly recommend all users to install this update as soon as possible.</source>
        <translation>最新版を速やかにインストールすることをおすすめします。</translation>
        
        <source>Your version of LameXP is still up-to-date. Please check for updates regularly!</source>
        <translation>お使いの LameXP はまだ最新版です。定期的にアップデートを確認してください！</translation>```

**Comment by lordmulder** [comment]
> 
> 
> Hi! lordmulder.
> 
> I optimized translation for Update Maneger.
> 
> ```
>         <source>LameXP is free software and release versions won&apos;t expire.</source>
>         <translation type="unfinished">LameXP はフリーソフトで正式リリース版の有効期限はありません。</translation>
> 
>         <source>Latest version available:</source>
>         <translation>利用可能な最新版 :</translation>
>         
>         <source>We highly recommend all users to install this update as soon as possible.</source>
>         <translation>最新版を速やかにインストールすることをおすすめします。</translation>
>         
>         <source>Your version of LameXP is still up-to-date. Please check for updates regularly!</source>
>         <translation>お使いの LameXP はまだ最新版です。定期的にアップデートを確認してください！</translation>```
> ```

Thank you!

_Added:_
https://github.com/lordmulder/LameXP/commit/2660e2089fcc3dde874fb10fd3b37beda5152278

**Pull request closed without merging**
