### PR TITLE
Create LameXP_PT_BR.ts

### PR DESCRIPTION
**Pull request by Felipefpl**
Added a brazilian portuguese translation for lamexp.

### CODE REVIEW

**Comment by lordmulder** [comment]
Why you have modified `LameXP_EN.ts` in-place rather than add `LameXP_BR.ts` ❓ 

Regards.

**Comment by Felipefpl** [comment]
i didnt want to download the file to translate and upload it, it was faster this way. ;)

**Comment by lordmulder** [comment]
Your file is very incomplete, though. You should copy **`Blank.ts`** (not into`LameXP_EN.ts`) to **`LameXP_BR.ts`** and then start translating in the Qt Linguist tool. For details, please see guide here:

http://lamexp.sourceforge.net/doc/Translate.html

Regards.

**Comment by Felipefpl** [comment]
Ok then (although i dont understand why there are several translations based in the file in the folder where the main file is)

**Comment by lordmulder** [comment]
**`Blank.ts`** is the "template" translation file, generated by Qt `lupdate.exe` straight from the `*.h` and `*.cpp` files.

The general approach is to copy **`Blank.ts`** to `**`LameXP_XX.ts`**` for each translation (language) and then start translating.

Regards.

**Comment by Felipefpl** [comment]
ok, thanks for the info.

**Pull request closed without merging**
